source 'https://github.com/CocoaPods/Specs.git'

# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"
#use_frameworks!

target "Decktracker" do
pod "ActionSheetPicker-3.0"
pod "AFNetworking"
pod "Appirater_ios8"
pod "CAAnimationBlocks"
pod "CAAnimation-EasingEquations"
pod "CorePlot"
pod "CSStickyHeaderFlowLayout"
pod "Dropbox-Sync-API-SDK"
pod "EDStarRating"
pod 'Fabric'
pod 'Crashlytics'
pod "Facebook-iOS-SDK"
pod "GoogleAnalytics"
pod "HMSegmentedControl"
pod "hpple"
pod "InAppSettingsKit"
pod "JJJUtils"
pod "LMAlertView"
pod "MBProgressHUD"
pod "Parse"
pod "ParseFacebookUtils"
pod "ParseTwitterUtils"
pod "ParseUI"
pod "PureLayout"
#pod "vfrReader", '~> 2.8.5'
pod "XLForm"

end


