source 'https://github.com/CocoaPods/Specs.git'

# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"
`$(inherited)`

target "Decktracker" do
pod "ActionSheetPicker-3.0"
pod "AFNetworking"
pod "CAAnimationBlocks"
pod "CAAnimation-EasingEquations"
pod "CorePlot"
pod "CSStickyHeaderFlowLayout"
pod "Dropbox-Sync-API-SDK"
pod "EDStarRating"
pod "Facebook-iOS-SDK"
pod "FFCircularProgressView"
pod "GoogleAnalytics-iOS-SDK"
pod "hpple"
pod "InAppSettingsKit"
pod "LMAlertView"
pod "MagicalRecord"
pod "MBProgressHUD"
pod "Parse"
pod "ParseFacebookUtils"
pod "ParseUI"
pod "PureLayout"
#pod "vfrReader", '~> 2.8.5'
pod "XLForm"


end


