# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"
`$(inherited)`

target "Decktracker" do

pod "AFNetworking"
pod "box-ios-sdk-v2"
pod "CorePlot"
pod "Dropbox-Sync-API-SDK"
pod "Google-API-Client"
pod "GoogleAnalytics-iOS-SDK"
pod "InAppSettingsKit"
pod "hpple"
pod "MagicalRecord"
pod "MBProgressHUD"

end


