# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"
`$(inherited)`

target "Decktracker" do

pod "AFNetworking"
pod "Dropbox-Sync-API-SDK"
pod "GoogleAnalytics-iOS-SDK"
pod "hpple"
pod "MagicalRecord"
pod "MBProgressHUD"

end


