source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"
#use_frameworks!

target "DataSource" do
pod "hpple"
pod "JJJUtils/OSX"
#pod "Parse"
pod "Realm", '0.94.0' 
end


